### ISSUE TITLE
XEN for S4SK will not build

### ISSUE THREAD

**Issue by mdege** [xen-troops/meta-xt-prod-devel-rcar-gen4#97]
The s4sk compatible string for optee-os is missing in: .../layers/meta-xt-domx-gen4/recipes-security/optee/optee.inc

**Comment by mdege** [comment]
[0001-fix-optee-os-compatible-for-s4sk.patch](https://github.com/user-attachments/files/17095419/0001-fix-optee-os-compatible-for-s4sk.patch)

**Comment by rshym** [comment]
Thanks for the finding and the providing of the proper patch. We will merge it.

**Comment by rshym** [comment]
@mdege I made PR with your patch https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/pull/98.
Could you please take a look.
If you don't mind, I will slightly update the commit message as suggested by our reviewer.

**Comment by rshym** [comment]
The patch is merged.

Thanks for the fix.
